---
driver:
  name: podman

platforms:
  - name: ubuntu-22.04
    image: docker.io/olge404/molecule:ubuntu-22.04-20240602100738
    pre_build_image: true
    groups:
      - ubuntu

  - name: alpine-3.20
    image: docker.io/olge404/molecule:alpine-3.20-20240602100802
    pre_build_image: true

  - name: almalinux-9.4
    image: docker.io/olge404/molecule:almalinux-9.4-20240608104813
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      ubuntu:
        packages_base:
          git: "1:2.34.1-1ubuntu1.11"
          gh: "2.50.0"
          terraform: ""

    host_vars:
      ubuntu-22.04:
        packages_extra:
          git: "1:2.45.2-0ppa1~ubuntu22.04.1"

        packages_repos:
          # See https://www.git-scm.com/download/linux
          git:
            repo: ppa:git-core/ppa
            
          # See https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
          hashicorp:
            repo: deb [signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com jammy main
            key_url: https://apt.releases.hashicorp.com/gpg
            key_dearmor: true

          # See https://github.com/cli/cli/blob/trunk/docs/install_linux.md#debian-ubuntu-linux-raspberry-pi-os-apt
          github:
            repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/github.gpg] https://cli.github.com/packages stable main
            key_url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            key_dearmor: false

      almalinux-9.4:
        packages_base:
          terraform: ""
          gh: "2.50.0-1"
          git: "2.43.0-1.el9"

        packages_repos:
          # See https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli
          hashicorp:
            repo: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

          # See https://github.com/cli/cli/blob/trunk/docs/install_linux.md#fedora-centos-red-hat-enterprise-linux-dnf
          github:
            repo: https://cli.github.com/packages/rpm/gh-cli.repo

      alpine-3.20:
        packages_base:
          github-cli@edge: "2.47.0-r3"
          git: "2.45.2-r0"
          curl: ""

        packages_repos:
          # See https://github.com/cli/cli/blob/trunk/docs/install_linux.md#alpine-linux
          edge:
            repo: http://dl-cdn.alpinelinux.org/alpine/edge/community
