---
- name: Converge
  hosts: all
  strategy: free
  gather_facts: false
  tasks:
    - name: "Include {{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }} role"
      tags: skip_ansible_lint
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
