---
namespace: olge404
name: unix
version: 0.7.0
readme: README.md
description: Streamline package installation, configuration and setup tasks for unix based distros.
authors:
  - OlGe404

tags:
  - linux
  - unix
  - packages
  - ubuntu
  - debian
  - linuxmint

repository: https://github.com/OlGe404/olge404.unix
documentation: https://github.com/OlGe404/olge404.unix/blob/main/README.md
homepage: https://github.com/OlGe404/olge404.unix
issues: https://github.com/OlGe404/olge404.unix/issues
build_ignore:
  - _old
  - .github
  - .molecule
  - .venv
  - .vscode
  - playbooks
  - scripts
  - .gitignore
  - requirements.txt
  - setup.json
  - to-dos.md

license:
  - Apache-2.0

dependencies:
  community.general: 10.1.0
