---
namespace: olge404
name: unix
version: 0.1.0
readme: README.md
description: Streamline package installation and configuration for unix based distros.
authors:
  - OlGe404

tags:
  - linux
  - unix
  - packages
  - ubuntu
  - debian
  - rhel
  - almalinux
  - alpine
  - linuxmint

repository: https://github.com/OlGe404/olge404.unix
documentation: https://github.com/OlGe404/olge404.unix/blob/main/README.md
homepage: https://github.com/OlGe404/olge404.unix
issues: https://github.com/OlGe404/olge404.unix/issues
build_ignore:
  - _old
  - .github
  - .molecule
  - .venv
  - .vscode
  - scripts
  - requirements.txt
  - to-dos.md

license:
  - Apache-2.0

dependencies: {}
  # community.general: 10.1.0
