---
# Used to map ansible_facts['architecture'] values to valid DEB 822 architecture values
# when adding apt repos
apt_deb_architectures:
  armv6l: armhf
  armv7l: armhf
  aarch64: arm64
  x86_64: amd64
  i386: i386
