---
- name: Ensure facts are gathered
  when: ansible_facts['os_family'] is undefined
  ansible.builtin.setup:
    gather_subset:
      - os_family

- name: Print os_family
  ansible.builtin.debug:
    var: ansible_facts['os_family']

- name: Merge base and extra packages
  ansible.builtin.set_fact:
    merged_packages: "{{ packages_base | combine(packages_extra) }}"

- name: Create list of packages to install
  loop: "{{ merged_packages | dict2items }}"
  ansible.builtin.set_fact:
    packages: "{{ packages |  default([]) + [item.key ~ ('=' ~ item.value if item.value else '')] }}"

- name: Include os_family dependent tasks
  when: packages | length > 0
  block:
    - name: Include apt.yaml
      when: ansible_facts['os_family'] == "Debian"
      ansible.builtin.include_tasks:
        file: apt.yml

    - name: Include apk.yaml
      when: ansible_facts['os_family'] == "Alpine"
      ansible.builtin.include_tasks:
        file: apk.yml

    - name: Include dnf.yaml
      when: ansible_facts['os_family'] == "RedHat"
      ansible.builtin.include_tasks:
        file: dnf.yml
