---
# - name: Assert vars have the correct type
#   ansible.builtin.assert:
#     quiet: true
#     that:
#       - apt_packages is mapping
#       - apt_packages_overwrite is mapping
#       - apt_repos is mapping

#     fail_msg: >-
#       The vars 'apt_packages', 'apt_packages_overwrite' and 'apt_repos' need to be of type 'dict'.

- name: Ensure facts are gathered
  when:
    - ansible_facts['architecture'] is undefined
    - ansible_facts['distribution_release'] is undefined
  ansible.builtin.setup:
    gather_subset:
      - architecture
      - distribution_release

- name: Ensure necessary packages are installed
  become: true
  ansible.builtin.apt:
    name:
      - gpg
      - software-properties-common

- name: Include repos.yml
  ansible.builtin.include_tasks:
    file: repos.yml

- name: Include packages.yml
  ansible.builtin.include_tasks:
    file: packages.yml
