---
- name: Merge apt_packages and apt_packages_overwrite
  ansible.builtin.set_fact:
    merged_apt_packages: "{{ apt_packages | combine(apt_packages_overwrite) }}"

- name: Create list of packages to install
  loop: "{{ merged_apt_packages | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  ansible.builtin.set_fact:
    packages: "{{ packages | default([]) + [ item.key ~ ('=' ~ item.value if item.value else '') ] }}"

- name: "Install apt packages: {{ packages | join(', ') }}"
  when:
    - packages is defined
    - packages | length > 0
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
