---
- name: Ensure dnf-plugins-core package
  become: true
  ansible.builtin.dnf:
    name: dnf-plugins-core

- name: Validate 'distro_packages_repos' against dnf JSON schema
  with_dict: "{{ distro_packages_repos }}"
  loop_control:
    label: "{{ item.key }}"
  ansible.utils.validate:
    data: "{{ item.value }}"
    engine: ansible.utils.jsonschema
    criteria:
      - "{{ lookup('file', '{{ role_path }}/files/dnf_repos.json') }}"

- name: Add dnf repos
  become: true
  with_dict: "{{ distro_packages_repos }}"
  ansible.builtin.command: "dnf config-manager --add-repo {{ item.value.url }}"
  # DNF cli output is not idempotent, hence this command cannot be idempotent
  changed_when: false

- name: Update dnf repo cache
  become: true
  ansible.builtin.dnf:
    update_cache: true

- name: Format "distro_packages" to accommodate for DNF's versioning peculiarities
  ansible.builtin.set_fact:
    dnf_distro_packages: "{{ distro_packages | map('regex_replace', '=', '-') | list }}"

- name: "Install {{ dnf_distro_packages | join(', ') }}"
  become: true
  ansible.builtin.dnf:
    name: "{{ dnf_distro_packages }}"
    allowerasing: true
