---
galaxy_info:
  author: OlGe404
  company: ""
  description: Install vscode extensions.
  license: Apache-2.0
  min_ansible_version: "2.16.7"
  galaxy_tags:
    - linux
    - unix
    - vscode
    - extensions
