---
driver:
  name: docker

platforms:
  - name: bookworm
    image: docker.io/olge404/molecule:debian-12-20241227081030
    pre_build_image: true

  - name: noble
    image: docker.io/olge404/molecule:ubuntu-24.04-20241227081038
    pre_build_image: true

  - name: wilma
    image: docker.io/olge404/molecule:linux-mint-22-20241227081132
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
