---
driver:
  name: docker

platforms:
  - name: bookworm
    image: docker.io/olge404/molecule:debian-12-20241230112659
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
