---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: bookworm
    box: bento/debian-12
    # Tests may crash with less than 4096
    memory: 4096
    config_options:
      vm.boot_timeout: 300
    groups:
      - custom_daemon_conf

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
    verify: ../shared/verify.yml
  
  config_options:
    defaults:
      remote_user: vagrant

  inventory:
    group_vars:
      custom_daemon_conf:
        docker_ce_daemon_json:
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
