---
- name: Ensure parent dir for venv exists
  become: true
  ansible.builtin.file:
    state: directory
    path: "{{ pip_venv_dir | dirname }}"
    group: root
    mode: "0777"

- name: Create venv using python3
  ansible.builtin.command: "python3 -m venv {{ pip_venv_dir }}"
  args:
    creates: "{{ pip_venv_dir }}"
