---
- name: Check condition
  when: pip_packages | length > 0
  block:
    - name: Collect stats if venv exists
      ansible.builtin.stat:
        path: "{{ pip_venv_dir }}/bin/activate"
      register: pip_venv

    - name: Include create_venv.yml
      when: not pip_venv.stat.exists
      ansible.builtin.include_tasks:
        file: create_venv.yml

    - name: Update pip, setuptools and wheel in venv
      tags: skip_ansible_lint
      ansible.builtin.pip:
        virtualenv: "{{ pip_venv_dir }}"
        state: latest
        name:
          - pip
          - setuptools
          - wheel

    - name: Install pip packages in venv
      ansible.builtin.pip:
        name: "{{ pip_packages }}"
        virtualenv: "{{ pip_venv_dir }}"
