---
galaxy_info:
  author: https://github.com/OlGe404
  description: Installation of distribution packages and repositories for various distros.
  company: None
  license: Apache-2.0
  min_ansible_version: "2.13"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm

    - name: EL
      versions:
        - "8"
  galaxy_tags: []

dependencies: []
