---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: debian-bullseye
    image: debian-bullseye:latest
    pre_build_image: true

  - name: debian-bookworm
    image: debian-bookworm:latest
    pre_build_image: true

  - name: rhel-8
    image: rhel-8:latest
    pre_build_image: true

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        distro_packages:
          - git
          - curl
          - packer

    host_vars:
      debian-bullseye:
        distro_repositories:
          - name: hashicorp
            key_url: https://apt.releases.hashicorp.com/gpg
            repo: "deb https://apt.releases.hashicorp.com bullseye main"

      debian-bookworm:
        distro_repositories:
          - name: hashicorp
            key_url: https://apt.releases.hashicorp.com/gpg
            repo: "deb https://apt.releases.hashicorp.com bookworm main"

      rhel-8:
        distro_repositories:
          - repo: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

verifier:
  name: ansible
