---
namespace: olge404
name: os
version: 0.17.2
readme: README.md
authors:
  - https://github.com/OlGe404

description: >
  Various roles to simplifiy the OS setup and software installation in infrastructure automation 
  pipelines for linux.

license:
  - Apache-2.0

tags:
  - os
  - vm

dependencies: {}
repository: https://github.com/OlGe404/ansible-collections
documentation: README.md
homepage: https://github.com/OlGe404
issues: https://github.com/OlGe404/ansible-collections/issues
build_ignore: []
