---
driver:
  name: docker

platforms:
  - name: bookworm
    image: docker.io/olge404/molecule:debian-12-20241230112659
    pre_build_image: true
    groups:
      - pip_packages_default

  - name: noble
    image: docker.io/olge404/molecule:ubuntu-24.04-20241230112704
    pre_build_image: true
    groups:
      - pip_packages_added

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml

  inventory:
    group_vars:
      pip_packages_added:
        pip_packages:
          - ansible
          - molecule==24.12.0
