---
driver:
  name: docker

platforms:
  - name: bookworm
    image: docker.io/olge404/molecule:debian-12-20241230112659
    pre_build_image: true
    groups:
      - installed

  - name: noble
    image: docker.io/olge404/molecule:ubuntu-24.04-20241230112704
    pre_build_image: true
    groups:
      - installed

  - name: wilma
    image: docker.io/olge404/molecule:linux-mint-22-20241230112708
    pre_build_image: true
    groups:
      - not_installed

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml

  inventory:
    group_vars:
      installed:
        pip_packages:
          - ansible
          - molecule==24.12.0

    host_vars:
      noble:
        pip_venv_dir: /tmp/python/venv
