---
- name: Verify pip_packages_default
  hosts: pip_packages_default
  gather_facts: false
  pre_tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

  tasks:
    - name: Collect stats if venv exists
      ansible.builtin.stat:
        path: "{{ pip_venv_dir }}/bin/activate"
      register: pip_venv

    - name: Assert that pip_venv doesn't exist
      ansible.builtin.assert:
        that:
          - not pip_venv.stat.exists

- name: Verify pip_packages_added
  hosts: pip_packages_added
  gather_facts: false
  pre_tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

  tasks:
    - name: Run test commands
      tags: skip_ansible_lint
      loop:
        - ansible --version
        - molecule --version
      ansible.builtin.shell: "source {{ pip_venv_dir }}/bin/activate && {{ item }}"
      args:
        executable: /bin/bash
