---
- name: Prepare container to execute molecule tests
  hosts: all
  # Can't gather_facts until python is installed
  gather_facts: false
  tasks:
    - name: Install apt packages
      when: inventory_hostname in ["ubuntu-jammy", "debian-bullseye"]
      loop:
        - apt-get update
        - apt install -y python3 sudo ca-certificates
      ansible.builtin.raw: "{{ item }}"

    - name: Install dnf packages
      when: inventory_hostname in ["rhel-8"]
      loop:
        - dnf update
        - dnf install -y sudo
      ansible.builtin.raw: "{{ item }}"

    - name: Symlink python3 -> python for correct interpreter discovery
      ansible.builtin.command: ln -s /usr/bin/python3 /usr/bin/python

    - name: Check that gather_facts works now
      ansible.builtin.setup:
