galaxy_info:
  author: OlGe404
  company: ""
  description: >-
    Install distribution specific repos and packages in a generic,
    declarative and tested way.

  issue_tracker_url: https://github.com/OlGe404/olge404.unix/issues
  license: Apache-2.0
  min_ansible_version: "2.16.7"
  galaxy_tags:
    - linux
    - unix
    - distro_packages
    - ubuntu
    - debian
    - almalinux
    - rhel
    - alpine

  platforms:
    - name: Alpine
      versions:
        - all

    - name: EL
      versions:
        - "9"

    - name: Ubuntu
      versions:
        - jammy
