---
driver:
  name: vagrant
  provider:
    name: virtualbox

# Using less than 4096 memory on any instance leads to crashing tests
platforms:
  - name: bookworm
    box: bento/debian-12
    cpus: 2
    memory: 4096
    config_options:
      vm.boot_timeout: 300
    groups:
      - custom_daemon_conf

  - name: noble
    box: bento/ubuntu-24.04
    cpus: 2
    memory: 4096
    config_options:
      vm.boot_timeout: 300
    groups:
      - no_daemon_conf

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
  
  config_options:
    defaults:
      remote_user: vagrant

  inventory:
    group_vars:
      custom_daemon_conf:
        docker_ce_daemon_json:
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "10m",
              "max-file": "3"
            }
          }
