---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: noble
    box: bento/ubuntu-24.04
    # Tests may crash with less than 4096
    memory: 4096
    config_options:
      vm.boot_timeout: 300
    groups:
      - no_daemon_conf

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
    verify: ../shared/verify.yml
  
  config_options:
    defaults:
      remote_user: vagrant
