---
driver:
  name: docker

platforms:
  - name: debian-12
    image: docker.io/olge404/molecule:debian-12-20241219162345
    pre_build_image: true
    groups:
      - not-ubuntu

  - name: ubuntu-24.04
    image: docker.io/olge404/molecule:ubuntu-24.04-20241222185324
    pre_build_image: true
    groups:
      - ubuntu

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml
