---
- name: Verify
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

  tasks:
    - name: Ensure tomte works
      tags: skip_ansible_lint
      ansible.builtin.command: tomte versions
      register: tomte_version

    - name: Assert that configured version == installed version
      ansible.builtin.assert:
        that:
          - tuxedo_tomte_version in tomte_version.stdout
