---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: debian-bullseye
    image: debian:bullseye
    pre_build_image: true

  - name: ubuntu-jammy
    image: ubuntu:jammy
    pre_build_image: true

  - name: rhel-8
    image: registry.access.redhat.com/ubi8/ubi:latest
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    prepare: ../../../../shared/playbooks/prepare.yaml
    converge: ../../../../shared/playbooks/converge.yaml

  inventory:
    links:
      group_vars: ../../../../group_vars/
      host_vars: ../../../../host_vars/

verifier:
  name: ansible
