---
driver:
  name: docker

platforms:
  - name: noble
    image: docker.io/olge404/molecule:ubuntu-24.04-vscode-20250101170616
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../../../../.molecule/playbooks/converge.yml

  inventory:
    group_vars:
      all:
        vscode_extensions:
          - github.vscode-github-actions
          - hashicorp.hcl@0.5.0
