---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Ensure prerequisites for vscode
      become: true
      ansible.builtin.apt:
        name:
          - software-properties-common
          - libasound2t64

    - name: Ensure no prompting during vscode install
      tags: skip_ansible_lint
      become: true
      ansible.builtin.shell: echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections

    - name: Install vscode
      become: true
      ansible.builtin.apt:
        deb: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
