---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: List code extensions
      tags: skip_ansible_lint
      ansible.builtin.command: code --list-extensions --show-versions
      register: installed_extensions

    - name: Assert that extensions are installed
      ansible.builtin.assert:
        that:
          - "'github.vscode-github-actions' in installed_extensions.stdout"
          - "'hashicorp.hcl@0.5.0' in installed_extensions.stdout"
