---
name: Build and push a specific container image
on:
  push:
    paths: ".molecule/platforms/Dockerfile.*"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - run: |
          git fetch --unshallow
          echo "CHANGESET=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.molecule/platforms/Dockerfile')" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          if [ -n "$CHANGESET" ]; then
            for dockerfile in $CHANGESET; do
              scripts/build-container.sh $dockerfile
            done
          else
            echo "No changes for '.molecule/platforms/Dockerfile.*' detected."
          fi
