---
name: Build and push all container images
on:
  # Build once per month to keep dependencies from parent images up to date
  schedule:
    # - cron: "0 0 * * 1"
    - cron: '*/5 * * * *'  # This triggers the workflow every 5 minutes

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: scripts/build-container.sh
