---
name: Container images
on:
  # Run every monday at midnight (UTC) to keep dependencies from parent images up to date
  schedule:
    - cron: "0 0 * * 1"

  push:
    branches:
      - "*"

    paths:
      - ".molecule/platforms/Dockerfile.*"

    tags-ignore:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Necessary to extract the CHANGESET
          fetch-depth: 0

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: |
          CHANGESET=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.molecule/platforms/Dockerfile' | paste -sd " " -)

          if [ -n "$CHANGESET" ]; then
            for dockerfile in "$CHANGESET"; do
              scripts/docker-build.sh "$dockerfile"
            done
          else
            scripts/docker-build.sh
          fi
