---
name: Container images
on:
  # Run every monday at midnight (UTC) to keep dependencies in test platform images up to date
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: scripts/docker-build.sh
