---
name: Run collection and molecule tests
on:
  # Run every tuesday at midnight (UTC) to check if dependencies from parent images break molecule tests
  schedule:
    - cron: "0 0 * * 2"

  push:
    paths:
      - 'roles/**/defaults/**'
      - 'roles/**/files/**'
      - 'roles/**/molecule/**'
      - 'roles/**/tasks/**'
      - 'roles/**/vars/**'

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
        with:
          # Necessary to extract the CHANGESET
          fetch-depth: 0
      
      - run: scripts/python3-venv.sh
      - run: scripts/ansible-galaxy-requirements.sh
      - run: scripts/ansible-test-sanity.sh
      - run: |
          CHANGESET=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'roles/' | paste -sd " " -)
          echo "$CHANGESET" >> $GITHUB_ENV

      - run: |
          if [ -n "$CHANGESET" ]; then
            for filepath in "$CHANGESET"; do
              ROLE_NAME=$(echo $filepath | cut -d '/' -f2)
              scripts/molecule-test.sh $ROLE_NAME
            done
          else
            scripts/molecule-test.sh
          fi
